import fs from "node:fs";
import path from "node:path";
import { useStore } from "../src/lib/store";
import { getPendingDispatchCount, type WorkflowData } from "../src/lib/workflowSelectors";

function assert(condition: unknown, message: string) {
  if (!condition) throw new Error(message);
}

function getWorkflowData(): WorkflowData {
  const state = useStore.getState();
  return {
    tasks: state.tasks,
    questionnaires: state.questionnaires,
    submissions: state.submissions,
    reviews: state.reviews,
    projects: state.projects,
    typeTaskPackages: state.typeTaskPackages,
    signoffRecords: state.signoffRecords,
  };
}

function readFileSafe(relativePath: string) {
  const absolutePath = path.resolve(process.cwd(), relativePath);
  return fs.existsSync(absolutePath) ? fs.readFileSync(absolutePath, "utf8") : "";
}

const data = getWorkflowData();
const state = useStore.getState();

const assignedProjects = state.projects.filter(project => {
  const quest = state.questionnaires.find(q => q.id === project.briefId);
  return quest?.status === "ASSIGNED";
});

const packagesByProjectId = new Map<string, typeof state.typeTaskPackages>();
state.typeTaskPackages.forEach(pkg => {
  const existing = packagesByProjectId.get(pkg.projectId) || [];
  packagesByProjectId.set(pkg.projectId, [...existing, pkg]);
});

const projectsWithMissingPackages = assignedProjects.filter(project => {
  const packages = packagesByProjectId.get(project.id) || [];
  return packages.length === 0;
});

const autoGeneratedPackages = state.typeTaskPackages.filter(pkg => pkg.id.startsWith("ttp-auto-"));

const canceledStatuses = ["REJECTED"];
const canceledQuestionnaires = state.questionnaires.filter(q => canceledStatuses.includes(q.status));
const pendingDispatchCount = getPendingDispatchCount(data);
const expectedPendingCount = state.questionnaires.filter(q => 
  !canceledStatuses.includes(q.status) && q.status !== "ASSIGNED" && q.status !== "COMPLETED"
).length;

const taskBoardContent = readFileSafe("src/components/pages/TaskBoard.tsx");
const reportContent = readFileSafe("src/components/pages/analytics/PerformanceReport.tsx");

const zhangLeiUserId = "u1";
const zhangLei = state.typeTaskPackages.some(pkg => pkg.assigneeId === zhangLeiUserId);
const zhangLeiPackages = state.typeTaskPackages.filter(pkg => pkg.assigneeId === zhangLeiUserId);
const zhangLeiPending = zhangLeiPackages.filter(pkg => pkg.status === "待提交");
const zhangLeiSignoff = zhangLeiPackages.filter(pkg => pkg.status === "待需求方审核");
const zhangLeiRevision = zhangLeiPackages.filter(pkg => pkg.status === "需修改");
const zhangLeiPassed = zhangLeiPackages.filter(pkg => pkg.status === "已通过");

const zhangLeiSignoffHasUrl = zhangLeiSignoff.every(pkg => {
  const submission = state.submissions.find(s => s.typeTaskPackageId === pkg.id);
  return submission?.signoffUrl;
});

const zhangLeiRevisionHasFeedback = zhangLeiRevision.every(pkg => pkg.latestFeedback);

const zhangLeiPassedHasRecord = zhangLeiPassed.every(pkg => {
  return state.signoffRecords.some(r => r.typeTaskPackageId === pkg.id && r.result === "passed");
});

const validation = {
  projectStats: {
    totalAssignedProjects: assignedProjects.length,
    originallyMissingPackages: projectsWithMissingPackages.length,
    autoGeneratedPackageCount: autoGeneratedPackages.length,
    stillMissingPackages: assignedProjects.filter(p => (packagesByProjectId.get(p.id) || []).length === 0).length,
  },
  canceledStatus: {
    canceledStatusValues: [...new Set(state.questionnaires.filter(q => 
      q.status === "REJECTED" || q.status.toLowerCase().includes("cancel")
    ).map(q => q.status))] as string[],
    canceledNotInPending: canceledQuestionnaires.every(q => {
      const isPending = state.questionnaires.filter(q2 => 
        !canceledStatuses.includes(q2.status) && q2.status !== "ASSIGNED" && q2.status !== "COMPLETED"
      ).some(q2 => q2.id === q.id);
      return !isPending;
    }),
    pendingCountMatches: pendingDispatchCount === expectedPendingCount,
  },
  taskBoard: {
    headerHasBrandRequester: taskBoardContent.includes('<div>品牌/需求方</div>'),
    projectColumnOnlyHasId: taskBoardContent.includes('<div style={{ fontSize: 14, fontWeight: 900, color: TEXT_MAIN }}>{row.project.projectName}</div>') &&
                           taskBoardContent.includes('<div style={{ marginTop: 4, fontSize: 12, color: TEXT_SUB }}>{row.project.projectCode}</div>') &&
                           taskBoardContent.includes('{packages.map(pkg => (<span key={pkg.id}'),
    deliverableTagFormatCorrect: taskBoardContent.includes('{pkg.deliverableType} × {pkg.deliverableItems.length}'),
    tagInProgressColumn: taskBoardContent.includes('<div className="flex items-center gap-[8px]" style={{ flexWrap: "wrap" }}>{packages.map(pkg =>'),
  },
  report: {
    noExternalBrandDistribution: !reportContent.includes("外部品牌分布"),
    hasBrandTeamDistribution: reportContent.includes("品牌 / 团队分布"),
  },
  zhangLeiTasks: {
    userExists: !!zhangLei,
    hasEnoughPackages: zhangLeiPackages.length >= 4,
    hasPending: zhangLeiPending.length >= 1,
    hasSignoff: zhangLeiSignoff.length >= 1,
    hasRevision: zhangLeiRevision.length >= 1,
    hasPassed: zhangLeiPassed.length >= 1,
    signoffHasUrl: zhangLeiSignoff.length === 0 || zhangLeiSignoffHasUrl,
    revisionHasFeedback: zhangLeiRevision.length === 0 || zhangLeiRevisionHasFeedback,
    passedHasRecord: zhangLeiPassed.length === 0 || zhangLeiPassedHasRecord,
    packageCount: zhangLeiPackages.length,
    pendingCount: zhangLeiPending.length,
    signoffCount: zhangLeiSignoff.length,
    revisionCount: zhangLeiRevision.length,
    passedCount: zhangLeiPassed.length,
  },
};

assert(validation.projectStats.totalAssignedProjects >= 1, "Should have assigned projects");
assert(validation.projectStats.stillMissingPackages === 0, "All assigned projects should have TypeTaskPackage");
assert(validation.canceledStatus.canceledNotInPending, "Canceled questionnaires should not be counted in pending");
assert(validation.canceledStatus.pendingCountMatches, "Pending dispatch count should match expected");
assert(validation.taskBoard.headerHasBrandRequester, "TaskBoard header should have '品牌/需求方'");
assert(validation.taskBoard.projectColumnOnlyHasId, "Project column should only show project name and ID");
assert(validation.taskBoard.deliverableTagFormatCorrect, "Deliverable tags should use '类型 × 数量' format");
assert(validation.taskBoard.tagInProgressColumn, "Deliverable tags should be in progress column");
assert(validation.report.noExternalBrandDistribution, "Report should not contain '外部品牌分布'");
assert(validation.report.hasBrandTeamDistribution, "Report should contain '品牌 / 团队分布'");
assert(validation.zhangLeiTasks.userExists, "张磊用户应该存在");
assert(validation.zhangLeiTasks.hasEnoughPackages, "张磊应该至少有4条任务");
assert(validation.zhangLeiTasks.hasPending, "张磊应该有待提交任务");
assert(validation.zhangLeiTasks.hasSignoff, "张磊应该有待需求方审核任务");
assert(validation.zhangLeiTasks.hasRevision, "张磊应该有需修改任务");
assert(validation.zhangLeiTasks.hasPassed, "张磊应该有已通过任务");
assert(validation.zhangLeiTasks.signoffHasUrl, "待需求方审核任务应该有signoffUrl");
assert(validation.zhangLeiTasks.revisionHasFeedback, "需修改任务应该有退回反馈");
assert(validation.zhangLeiTasks.passedHasRecord, "已通过任务应该有通过记录");

console.log(JSON.stringify({
  ok: true,
  result: {
    projectStats: validation.projectStats,
    canceledStatus: {
      ...validation.canceledStatus,
      totalCanceled: canceledQuestionnaires.length,
    },
    taskBoard: validation.taskBoard,
    report: validation.report,
    zhangLeiTasks: validation.zhangLeiTasks,
    summary: {
      assignedProjects: validation.projectStats.totalAssignedProjects,
      originallyMissing: validation.projectStats.originallyMissingPackages,
      autoGenerated: validation.projectStats.autoGeneratedPackageCount,
      stillMissing: validation.projectStats.stillMissingPackages,
      canceledQuestionnaires: canceledQuestionnaires.length,
      pendingDispatchCount,
      zhangLeiPackages: validation.zhangLeiTasks.packageCount,
    },
  },
}, null, 2));
